version: "3.0"
services:
  docker-mysql:
    image: mysql:8.0.31
    container_name: unique-docker-mysql
    volumes:
      - ./mysql-init-files/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_DATABASE: UA
      MYSQL_ROOT_PASSWORD: 12345678
      TZ: Asia/Seoul
    ports:
      - "3309:3309"

  
  docker-redis:
    image: redis:latest
    container_name: unique-docker-redis
    ports:
      - "6377:6377"
