version: "3.0"
services:
  unique-auction:
    image: uniqueauction-img-green

    container_name: uniqueauction-green

    environment:
      - LANG=ko_KR.UTF-8
      - UWSGI_PORT=8080

    ports:
      - '7102:8080'
