version: "3.0"
services:
  unique-auction:
    image: uniqueauction-img-blue

    container_name: uniqueauction-blue

    environment:
      - LANG=ko_KR.UTF-8
      - UWSGI_PORT=8080

    ports:
      - '7101:8080'
