version: "3.0"
services:
  docker-mysql:
    image: mysql
    container_name: unique-docker-mysql
    volumes:
      - ./mysql-init-files/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_DATABASE: UA
      MYSQL_ROOT_PASSWORD: 12345678
      TZ: Asia/Seoul
    ports:
      - "13309:3306"

  
  docker-redis:
    image: redis:latest
    container_name: unique-docker-redis
    ports:
      - "16379:6379"
