version: "3.0"
services:
  unique-auction:
    image: vymr1000/unique-auction

    container_name: unique-auction-blue

    environment:
      - LANG=ko_KR.UTF-8
      - UWSGI_PORT=8080

    ports:
      - '7101:8080'
