version: "3.0"
services:
  # Application server 1 (green)
  green-server-1:
    image: vymr1000/unique-auction
    container_name: green-server-1
    environment:
      - LANG=ko_KR.UTF-8
      - UWSGI_PORT=8080
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
    ports:
      - '7103:8080'

  # Application server 2 (green)
  green-server-2:
    image: vymr1000/unique-auction
    container_name: green-server-2
    environment:
      - LANG=ko_KR.UTF-8
      - UWSGI_PORT=8080
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
    ports:
      - '7104:8080'