spring:
  profiles: real1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.67.132.139:13309/UA?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: uauser
    password: 12345678

  jpa:
    show-sql: true

  redis:
    host: 118.67.132.139
    port: 16379
    password: 12345678

  session:
    store-type: redis
    redis:
      flush-mode: on_save
server:
  port: 8081
---

spring:
  profiles: real2
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.67.132.139:13309/UA?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: uauser
    password: 12345678

  jpa:
    show-sql: true

  redis:
    host: 118.67.132.139
    port: 16379
    password: 12345678

  session:
    store-type: redis
    redis:
      flush-mode: on_save
server:
  port: 8082



