spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/UA?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 12345678


  config:
    activate:
      on-profile: local-main

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    generate-ddl: true

  redis:
    host: localhost
    port: 6379
    password: 12345678

  session:
    store-type: redis
    redis:
      flush-mode: on_save

  sql:
    init:
      schema-locations: classpath*:mysql-init-files/schema.sql

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: "trades"

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true