spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.67.132.139:13309/UA?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: uauser
    password: 12345678

  config:
    activate:
      on-profile: prod-main

  jpa:
    show-sql: true

  redis:
    host: 118.67.132.139
    port: 16379
    password: 12345678

  session:
    store-type: redis
    redis:
      flush-mode: on_save

  kafka:
    bootstrap-servers: 118.67.132.139:9092
    consumer:
      group-id: "bid-group"

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true