spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # url: jdbc:mysql://docker-mysql:3306/UA?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    url: jdbc:mysql://localhost:3306/UA?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 12345678

  jpa:
    show-sql: true


  redis:
    #    host: docker-redis
    host: 127.0.0.1
    port: 6379


  session:
    store-type: redis
    redis:
      flush-mode: on_save
