# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

#permissions:
 # contents: read

jobs:
  build:

    runs-on: ubuntu-latest    

    steps:
    # 코드 체크 아웃
    - uses: actions/checkout@v3
    
    # 자바 버전 설정 11버전
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
   # 코드 포맷 
  # - name: code Formt Check
  #    run:
   # 테스트는 전부 성공해야 통과.     
    - name: Test with Gradle
      run: ./gradlew --info test
      
      
   # 테스트 후 결과를 보기 위한 단계 추가
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: ${{ always() }}
      with:
       files: .github/test-results/*.xml
     
     
     
    # 캐싱 추가 테스트를 더빠르게 해준다. 캐싱을 함으로서 재컴파일 필요 없고 
    # 종속성된 파일들을 원격 저장소에서 다운로드 할필요없이 캐시 복원된다 
    - name: Cleanup Gradle Cache
      if: ${{ always() }}
      run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties
      
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
